### ISSUE TITLE
TODO Command

### ISSUE THREAD

**Issue by brucewrks** [websharks/ws-commander#1]
Possibly could be done through an integration with iDoneThis, or maybe through Git, using a `.md` file in the websharks/team repo.

Example: `ws todo 'Write a KB Article on...`

@websharks/team Any thoughts?

**Comment by raamdev** [comment]
> through an integration with iDoneThis

I prefer all iDoneThis integration to happen through Slack... @jaswsinc opened an issue for this yesterday: websharks/websharks-inc.com#69

> or maybe through Git, using a .md file in the websharks/team repo.

That's an interesting idea, but I like the iDoneThis TODOs and I wouldn't want to have TODOs spread around in too many places...

**Comment by jaswrks** [comment]
I like iDoneThis for TODO lists also, because it makes it easy to collaborate/comment/share.

A command-line tool that would utilize the iDoneThis API to create a TODO item. I explored this recently with the tool provided by iDoneThis for command line use, but it's really just a dirty example they've written, nothing official yet.

If you create a command line tool that was wrapped up into a Homebrew package specifically for use with iDoneThis, I think that would be really useful to a lot of folks, and you could even submit that for inclusion at iDoneThis.com.

See: https://idonethis.com/apps-integrations/

![2015-01-23_16-38-54](https://cloud.githubusercontent.com/assets/1563559/5885618/913071f2-a31e-11e4-97b4-2159011f3032.png)

> or maybe through Git, using a .md file in the websharks/team repo.

I agree with Raam. I'd like to keep them in iDoneThis if we can.

> Possibly could be done through an integration with iDoneThis

Increasing the number of ways that we can integrate with iDoneThis seems productive to me.

**Comment by jaswrks** [comment]
BTW: I played with that Jinni app that is integrated with iDoneThis. It's works OK. It was a bit confusing when I started, but now it seems fine. Not sure how much I will actually use that, but it might be worth taking a look at. You enter TODO items from the menu bar on your Mac, and then checking them off sends it to iDoneThis. https://itunes.apple.com/us/app/jinni/id777209218?mt=12

**Comment by brucewsinc** [comment]
test comment

**Comment by brucewrks** [comment]
I'm starting work on this, and a `ws done` command.

**Comment by brucewrks** [comment]
Done. You can upgrade by running the following:

```
cd ~/ws-commander && git pull;
cd ~ && npm install -g ws-commander;
ws-install;
```
